const messages = [
  {
    username: 'david',
    message: '(Message 1) This Message will self Destruct in 5 seconds',
    selfDestruct: true,
    destructAt: 5000 + Date.now(),
    totalMs: 5000,
    hasExpired: false,
    messageId: 7093,
  },
  {
    username: 'lisa',
    message: '(Message 2) This Message will self Destruct in 10 seconds.',
    selfDestruct: true,
    destructAt: 10000 + Date.now(),
    totalMs: 10000,
    hasExpired: false,
    messageId: 9816,
  },
  {
    username: 'francis',
    message: '(Message 3) This Message will self Destruct in 20 seconds.',
    selfDestruct: true,
    destructAt: 20000 + Date.now(),
    totalMs: 20000,
    hasExpired: false,
    messageId: 6534,
  },
  {
    username: 'sonrisa',
    message: '(Message 4) This Message will self Destruct in 30 seconds.',
    selfDestruct: true,
    destructAt: 30000 + Date.now(),
    totalMs: 30000,
    hasExpired: false,
    messageId: 6279,
  },
  {
    username: 'david',
    message: '(Message 5) This Message will not self destruct',
    selfDestruct: false,
    destructAt: -1,
    totalMs: -1,
    hasExpired: false,
    messageId: 4141,
  },
  {
    username: 'lisa',
    message: '(Message 6) This Message will self Destruct in 1 minute.',
    selfDestruct: true,
    destructAt: 60000 + Date.now(),
    totalMs: 60000,
    hasExpired: false,
    messageId: 9452,
  },
  {
    username: 'francis',
    message: '(Message 7) This message will not self destruct.',
    selfDestruct: false,
    destructAt: -1,
    totalMs: -1,
    hasExpired: false,
    messageId: 8911,
  },
  {
    username: 'sonrisa',
    message: '(Message 8) This Message will self Destruct in 2 minutes.',
    selfDestruct: true,
    destructAt: 120000 + Date.now(),
    totalMs: 120000,
    hasExpired: false,
    messageId: 1386,
  },
];

const users = [
  { username: 'david' },
  { username: 'lisa' },
  { username: 'francis' },
  { username: 'sonrisa' },
];

module.exports = { users, messages };
