export const SET_USERNAME = 'SET_USERNAME';
export const LOAD_MESSAGES_REQUEST = 'LOAD_MESSAGES_REQUEST';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAILURE = 'LOAD_MESSAGES_FAILURE';
export const UPDATE_TIMESTAMP = 'UPDATE_TIMESTAMP';
